/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RustInterface */

#ifndef _Included_RustInterface
#define _Included_RustInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RustInterface
 * Method:    sendMessage
 * Signature: (III[BZ)Z
 */
JNIEXPORT jboolean JNICALL Java_RustInterface_sendMessage
  (JNIEnv *, jobject, jint, jint, jint, jbyteArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
