[package]
name = "rust_program"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zermia_lib = { path = "/home/hugocardante/JHShadow/src/lib/zermia_lib" } 