#!/usr/bin/env bash


echo "Zermia example..."


# first argument is the path to shadow
if [ "$#" -ge 1 ]; then
    echo "Prepending $1 to PATH"
    export PATH="$1:${PATH}"
fi

# Removing shadow.data
if [ -d "shadow.data" ]; then
  echo "  "
  printf '%s\n' "Removing directory shadow.data"
  rm -rf "shadow.data"
  echo "  "
fi

shadow shadow.yaml > hugo.log

# Printing host files
echo;
for file in shadow.data/hosts/*/*.stdout;
  do 
    echo "##########################################"
    echo $file 
    echo;
    cat $file; 
    echo "##########################################"
    echo;
  done
